# Statically link the MSVC C runtime on Windows so the release binaries do
# not depend on VCRUNTIME140.dll / the VC++ Redistributable being installed.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
